### ISSUE TITLE
Support for Ingress Resource Creation with ToolHive Operator

### ISSUE THREAD

**Issue by ChrisJBurns** [StacklokLabs/toolhive#315]
We've had feedback that separately creating an Ingress record using YAML manifests isn't great and that it would be worth considering creating the Ingress object with ToolHive Operator as part of the `MCPServer`.

For example:
```yaml
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: fetch
  namespace: toolhive-system
spec:
  image: docker.io/mcp/fetch
  transport: stdio
  port: 8080
  permissionProfile:
    type: builtin
    name: network
  ingress:
     enabled: true
     ...
     ...
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
```
